<h1 align = "center">Practical 7: Vectors Part 2</h1>

In [3]:
import numpy as np

## Q1. Create a Python list representing vector v = [2,-1, 3] and multiply it by scalar 4.

In [1]:
v = [2, -1, 3]
sc = 4

sc * v

[2, -1, 3, 2, -1, 3, 2, -1, 3, 2, -1, 3]

Explanation: the result of multiplication is incorrect from the linear algebra perspective. because, according to the linear algebra rule: scalar number should be multiplied to each element of the vector instead of expanding the vector.

In [4]:
#converting the vector into numpy array

v = np.array(v)
sc * v

array([ 8, -4, 12])

## Q2. Given vector a = [5,-3] and scalar $\lambda$ =-2:

In [18]:
a = np.array([5, -3])
lmbd = -2

a_lmbd = a*lmbd
a_lmbd

array([-10,   6])

In [15]:
#comparing the madnitudes of the vectors

length_a = np.linalg.norm(a)
length_a_lmbd = np.linalg.norm(a_lmbd)
print(length_a)
print(length_a_lmbd)

5.830951894845301
11.661903789690601


Explanation: $\lambda$ extended the magnitude of the initial vector and changed the direction to the opposite side.

## Q3. Broadcasting

In [24]:
v1 = np.array([[1, 4, 2]]).T
v2 = np.array([[4, 2, 3, 2]])

print(v1.shape)
print(v2.shape)
print((v1+v2).shape)
print(v1 + v2)

(3, 1)
(1, 4)
(3, 4)
[[5 3 4 3]
 [8 6 7 6]
 [6 4 5 4]]


## Q4 . Create vector v = [1,2,3,4] and add scalar 5.

In [26]:
v = np.array([[1,2,3,4]])
sc = 5

print(v + sc)

[[6 7 8 9]]


Explanation: Numpy allows to do this just because it understands what's goin on, even though it's not acceptable in linear algebra.

## Q5. Given vector a = [1,2,3,4,5,6], compute its Euclidean norm manually and using NumPy.

In [28]:
a = [1,2,3,4,5,6]

mult = np.multiply(a, a)
summation = np.sum(mult)
norm1 = np.sqrt(summation)
print("manually: ", norm1)

norm2 = np.linalg.norm(a)
print("numpy: ", norm2)

manually:  9.539392014169456
numpy:  9.539392014169456


## Q6. Generate a random vector of length 10 and normalize it. Print the norm before and after normalization

In [36]:
length = 10
v = np.random.randn(length)
mag1 = np.linalg.norm(v)
print(norm1)
unit = v/np.linalg.norm(v)
mag2 = np.linalg.norm(unit)
print(mag2)

9.539392014169456
1.0


## Q7. Compute the dot product of vectors

a = [1,2,3,4,5,6] & b = [0,-4,3,-3,6,5]

In [42]:
a = np.array([1,2,3,4,5,6])
b = np.array([0,-4,3,-3,6,5])

ab1 = 0
#manual loop
for i in range(len(a)):
    ab1 += a[i] * b[i]
print(ab1)

#numpy.dot
ab2 = np.dot(a, b)
print(ab2)

49
49


## Q8. Verify the distributive property:

In [44]:
c = np.array([2,4,6,7,3,6])
print(np.dot(a, b+c))
print(np.dot(a, b) + np.dot(a, c))

156
156


## Q9: Compute the Euclidean distance matrix between every point in group A and every point in group B.

In [60]:
#Group A
A = np.array([
    [ 2, 1],
    [ 5, 4],
    [ 1, 6],
    [ 7, 2]
])
# Group B
B = np.array([
    [0, 0],
    [6, 3],
    [3, 5]
])

print(A.shape)
print(B.shape)

dist = np.sqrt(((A[:, np.newaxis, :] - B[np.newaxis, :, :]) ** 2).sum(axis=2))
dist

(4, 2)
(3, 2)


array([[2.23606798, 4.47213595, 4.12310563],
       [6.40312424, 1.41421356, 2.23606798],
       [6.08276253, 5.83095189, 2.23606798],
       [7.28010989, 1.41421356, 5.        ]])

In [ ]:
(A[:, np.newaxis, :] - B[np.newaxis, :, :])

array([[[-5, -5],
        [ 0, -1]],

       [[-4, -4],
        [ 1,  0]],

       [[-3, -3],
        [ 2,  1]]])